version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  dependencies:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - "node_modules"

  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run lint
          command: yarn htmllint *.html
            
  publish-to-staging:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn netlify deploy -p -d . -a ${NETLIFY_TOKEN} -s ${NETLIFY_STAGING_API_ID}
      - run:
          name: Execute E2E test by Autify
          command: |
            curl -XPOST -H "Authorization: Bearer ${AUTIFY_TOKEN}" https://app.autify.com/api/v1/schedules/4974
      - slack/notify:
          color: '#125d7d'
          message: (Staging) Hotel Example Site was successfully deployed

  publish-to-production:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn netlify deploy -p -d . -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}
      - slack/notify:
          color: '#3d7d12'
          message: (Production) Hotel Example Site was successfully deployed
      
workflows:
  version: 2
  Publish:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - publish-to-staging:
          filters:
            branches:
              only: development
          requires:
            - lint
      - publish-to-production:
          filters:
            branches:
              only: master
          requires:
            - lint
          
